// Project Euler
// Problem 12
// Highly divisible triangular number
// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

// Let us list the factors of the first seven triangle numbers:

//  1: 1
//  3: 1,3
//  6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// 36: 1,2,3,4,6,9,12,18,36

// We can see that 28 is the first triangle number to have over five divisors.

// What is the value of the first triangle number to have over five hundred divisors?

function countFactors(n) {
	var factorCount = 1;
	for (var i = 1; i <= n/2; i++) {
		if (n % i === 0) factorCount++;
	}
	return factorCount;
}

function findTrangularNumber() {
	var triangularNumber = 0;
	var i = 0;
	var factorCount = 0;

	while (factorCount <= 500) {
		i++;
		triangularNumber += i;
		if (triangularNumber % 2 === 0) {
			factorCount = countFactors(triangularNumber);
		}
	}

	return triangularNumber;
}

console.log(findTrangularNumber());